# Generated by Django 2.1.3 on 2018-12-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
