# Generated by Django 2.1.3 on 2019-01-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181207_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='Rank-Tree', max_length=20),
        ),
    ]
