# Generated by Django 2.1.3 on 2019-01-31 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190122_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
