# Generated by Django 2.1.3 on 2018-12-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20181205_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
