# Generated by Django 2.1.3 on 2018-12-12 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_questionset_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestScheduledSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('date_slot', models.ManyToManyField(related_name='scheduled_time', to='question.DateSlot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='question',
        ),
        migrations.RemoveField(
            model_name='subscriptionpackage',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='duration_time',
        ),
        migrations.AddField(
            model_name='questionset',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_sets', to='question.Course'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='basic', max_length=10),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='dateslot',
            name='time_slot',
            field=models.ManyToManyField(related_name='dates', to='question.TimeSlot'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='scheduled_time_slot',
            field=models.ManyToManyField(related_name='question_sets', to='question.TestScheduledSlot'),
        ),
    ]
