# Generated by Django 2.1.3 on 2018-12-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20181212_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testscheduledslot',
            name='date_slot',
        ),
        migrations.RemoveField(
            model_name='dateslot',
            name='date',
        ),
        migrations.AddField(
            model_name='dateslot',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dateslot',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='scheduled_time_slot',
            field=models.ManyToManyField(related_name='question_sets', to='question.DateSlot'),
        ),
        migrations.DeleteModel(
            name='TestScheduledSlot',
        ),
    ]
