# Generated by Django 2.1.3 on 2018-12-17 15:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20181213_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('-----', '-----'), ('basic', 'Basic'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='-----', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.RemoveField(
            model_name='subscriptionpackage',
            name='question_set',
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='question_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_packages', to='question.QuestionSet'),
        ),
    ]
