# Generated by Django 2.1.3 on 2019-01-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_auto_20181217_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('-----', '-----'), ('audio', 'Audio'), ('objective', 'Objective'), ('subjective', 'Subjective'), ('passage', 'Passage')], default='-----', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
