# Generated by Django 2.1.3 on 2019-01-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_auto_20190114_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='question_type',
            field=models.CharField(choices=[('-----', '-----'), ('audio', 'Audio'), ('objective', 'Objective'), ('subjective', 'Subjective'), ('passage', 'Passage')], default='-----', max_length=10),
        ),
        migrations.RemoveField(
            model_name='subscriptionpackage',
            name='question_set',
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='question_set',
            field=models.ManyToManyField(to='question.QuestionSet'),
        ),
    ]
