# Generated by Django 2.1.3 on 2019-01-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_auto_20190116_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpackage',
            name='scheduled_time_slot',
            field=models.ManyToManyField(related_name='subscription_packages', to='question.DateSlot'),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='scheduled_time_slot',
            field=models.ManyToManyField(blank=True, null=True, related_name='question_sets', to='question.DateSlot'),
        ),
    ]
