# Generated by Django 2.1.3 on 2019-01-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0016_auto_20190117_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpackage',
            name='time_duration',
            field=models.IntegerField(default=0),
        ),
    ]
