# Generated by Django 2.1.3 on 2019-01-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_subscriptionpackage_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpackage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
