# Generated by Django 2.1.3 on 2019-01-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0018_subscriptionpackage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='technology',
            field=models.CharField(choices=[('-----', '-----'), ('C', 'C'), ('C++', 'C++'), ('java', 'java'), ('Python', 'Python'), ('Javascript', 'Javascript')], default='-----', max_length=15),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('-----', '-----'), ('audio', 'Audio'), ('objective', 'Objective'), ('subjective', 'Subjective'), ('passage', 'Passage'), ('technical', 'Technical')], default='-----', max_length=15),
        ),
    ]
