# Generated by Django 2.1.3 on 2019-01-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0019_auto_20190119_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='technology',
            field=models.CharField(choices=[('-----', '-----'), ('c', 'C'), ('c++', 'C++'), ('java', 'Java'), ('python', 'Python'), ('javascript', 'Javascript')], default='-----', max_length=15),
        ),
    ]
