# Generated by Django 2.1.3 on 2019-01-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0021_auto_20190121_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('-----', '-----'), ('basic', 'Basic'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='-----', max_length=15),
        ),
    ]
