# Generated by Django 2.1.3 on 2019-01-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0022_auto_20190121_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioquestion',
            name='marks_per_question',
        ),
        migrations.RemoveField(
            model_name='passagequestion',
            name='marks_per_question',
        ),
    ]
