# Generated by Django 2.1.3 on 2019-02-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0024_auto_20190130_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionset',
            name='marks_per_question',
        ),
        migrations.AddField(
            model_name='questionset',
            name='marks_per_audio_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionset',
            name='marks_per_objective_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionset',
            name='marks_per_passage_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionset',
            name='marks_per_subjective_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionset',
            name='marks_per_technical_question',
            field=models.IntegerField(default=0),
        ),
    ]
