# Generated by Django 2.1.3 on 2019-02-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0025_auto_20190201_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpackage',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to='test_syllabus'),
        ),
    ]
